"""empty message

Revision ID: b8b991ddd5bb
Revises: e3f63c062eae
Create Date: 2022-01-23 00:33:14.239323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b991ddd5bb'
down_revision = 'e3f63c062eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('ticket_price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventsubscription',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eventid'], ['event.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userid', 'eventid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventsubscription')
    op.drop_table('event')
    # ### end Alembic commands ###
